package me.abarrow.ScalaSubNet.mal

object MALIDs {
  //many studios are missing the list of producers is way too long
  val studios = Map(
      1 -> "Studio Pierrot",
      2 -> "Kyoto Animation",
      3 -> "Gonzo",
      4 -> "Bones",
      5 -> "Bee Train",
      6 -> "Gainax",
      7 -> "J.C.Staff",
      8 -> "Artland",
      10 -> "Production I.G",
      11 -> "Madhouse",
      13 -> "Studio 4°C",
      14 -> "Sunrise",
      18 -> "Toei Animation",
      21 -> "Studio Ghibli",
      22 -> "Nippon Animation",
      27 -> "Xebec",
      28 -> "OLM, Inc.",
      30 -> "Ajia-Do",
      32 -> "Manglobe",
      34 -> "Hal Film Maker",
      35 -> "Seven Arcs",
      36 -> "Studio Gallop",
      37 -> "Studio Deen",
      38 -> "Arms",
      39 -> "Daume",
      41 -> "Statelight",
      43 -> "ufotable",
      44 -> "Shaft",
      47 -> "Khara",
      48 -> "AIC",
      51 -> "Diomedea",
      56 -> "A-1 Pictures",
      60 -> "Actas",
      65 -> "Tokyo Movie Shinsha",
      68 -> "Mushi Production",
      70 -> "Nomad",
      73 -> "TMS Entertainment",
      77 -> "APPP",
      81 -> "Radix",
      83 -> "AIC Spirits",
      84 -> "Studio Rikka",
      86 -> "Group TAC",
      88 -> "AIC A.S.T.A.",
      91 -> "feel.",
      94 -> "Telecom Animation Film",
      95 -> "Doga Kobo",
      96 -> "Yumeta Company",
      101 -> "Studio Hibari",
      103 -> "Tatsunoko Production",
      110 -> "Triangle Staff",
      112 -> "Brain's Base",
      120 -> "TNK",
      314 -> "White Fox",
      555 -> "Studio Chizu",
      858 -> "Wit Studio")
    
  val genres = Map(
      1 -> "Action",
      2 -> "Adventure",
      3 -> "Cars",
      4 -> "Comedy",
      5 -> "Dementia",
      6 -> "Demons",
      7 -> "Mystery",
      8 -> "Drama",
      9 -> "Ecchi",
      10 -> "Fantasy",
      11 -> "Game",
      12 -> "Hentai",
      13 -> "Historical",
      14 -> "Horror",
      15 -> "Kids",
      16 -> "Magic",
      17 -> "Martial Arts",
      18 -> "Mecha",
      19 -> "Music",
      20 -> "Parody",
      21 -> "Samurai",
      22 -> "Romance",
      23 -> "School",
      24 -> "Sci-Fi",
      25 -> "Shoujo",
      26 -> "Shoujo Ai",
      27 -> "Shounen",
      28 -> "Shounen Ai",
      29 -> "Space",
      30 -> "Sports",
      31 -> "Super Power",
      32 -> "Vampire",
      33 -> "Yaoi",
      34 -> "Yuri",
      35 -> "Harem",
      36 -> "Slice of Life",
      37 -> "Supernatural",
      38 -> "Military",
      39 -> "Police",
      40 -> "Psychological",
      41 -> "Thriller",
      42 -> "Seinen",
      43 -> "Josei")
      
  val statuses = Map(
      1 -> "Watching",
      2 -> "Completed",
      3 -> "On Hold",
      4 -> "Dropped",
      6 -> "Plan to Watch"
  )
}